routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'ReclamosController@index')->name('home');
Route::resource('user','UserController');
Route::resource('reclamos', 'ReclamosController');
Route::resource('configuraciones', 'SettingController');

Route::get('nuevo', 'ReclamosController@create');

Route::get('/ajax/crearcodigo', 'ReclamosController@ajxCrearCodigoReclamo');
Route::post('/ajax/registrar', 'ReclamosController@ajxRegistrarReclamo');
// Route::get('/ajax/inforeclamo', 'ReclamosController@ajxInfoReclamo');
// Route::get('/ajax/actualizarflagreclamo', 'ReclamosController@ajxActualizarFlagReclamo');

Route::get('/enviarmail','MailController@enviarEmail');

Route::any('/getcaptcha', 'CaptchaController@getCaptcha' );
Route::get('/refreshcapcha', 'CaptchaController@refreshCapcha');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'first_lastname', 'second_lastname', 'email', 'mobile', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function scopeValidarUsuario($query, $usuario, $clave)
    {	return $query->where('usuario', '=', $usuario)
        ->where('clave', '=', $clave)->get();

    }

    public function scopeInfoUsuario($query, $idUsuario)
    {	return $query->where('id', '=', $idUsuario)->get();  }

    public function scopeGetAdmin($query)
    {
        return $query->where('email', 'haraoz@sole.com.pe')->first();
    }

    public function scopeActualizarUsuario($query, $usuario)
    {
        $updateResult = $query->where('id', '=', $usuario["idUsuario"])
            ->update(array('usuario' => $usuario["usuario"],
                'clave' => $usuario["clave"],
                'nombre' => $usuario["nombre"],
                'email' => $usuario["email"]
            ));

        if($updateResult=="1")
        {   return true;    }

        return false;

    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Spatie\Permission\Models\Role;

;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function index()
    {
        $users = User::all();
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function create()
    {
        $roles = Role::pluck('name', 'name');

        return view('user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new User([
            'name' => $request->name,
            'first_lastname'=> $request->first_lastname,
            'second_lastname'=> $request->second_lastname,
            'email'=> $request->email,
            'mobile'=> $request->mobile,
            'password'=> bcrypt($request->password),
        ]);

        $user->save();
        $user->assignRole($request->role);
        return Redirect::route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function show($id)
    {
        return Redirect::route('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $success = false;

        return view('user.edit', compact('user', 'success'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function update(Request $request, $id)
    {
        $success = false;
        $request->validate([
            'name' => 'required|min:2|max:25',
            'first_lastname' => 'required|max:20',
            'second_lastname' => 'required|max:20',
            'email' => 'required|email|max:35',
            'mobile' => 'required|max:15',
        ]);

        $user = User::findOrFail($id);
        $user->name = $request->input('name');
        $user->first_lastname = $request->input('first_lastname');
        $user->second_lastname = $request->input('second_lastname');
        $user->email = $request->input('email');
        $user->mobile = $request->input('mobile');

        if (!empty($request->input('password')))
            $user->password = bcrypt($request->input('password'));

        if ($user->save()) {
            $success = 'Guardado correctamente';
        }

        return view('user.edit', compact('user', 'success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return Redirect::route('user.index');
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Cuenta de usuario</div>
                <div class="card-body">
                    {!! Form::open(['route' => ['user.store'], 'method' => 'post']) !!}
                        @csrf
                        <div class="form-group mb-4">
                            <label for="name">Nombres</label>
                            {!! Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'maxlength' => 25]) !!}
                        </div>
                        <div class="form-group mb-4">
                            <label for="first_lastname">Apellido Paterno</label>
                            {!! Form::text('first_lastname', null, ['class' => 'form-control', 'id' => 'first_lastname', 'maxlength' => 20]) !!}
                        </div>
                        <div class="form-group mb-4">
                            <label for="second_lastname">Apellido Materno</label>
                            {!! Form::text('second_lastname', null, ['class' => 'form-control', 'id' => 'second_lastname', 'maxlength' => 20]) !!}
                        </div>
                        <div class="form-group mb-4">
                            <label for="mobile">Celular</label>
                            {!! Form::text('mobile', null, ['class' => 'form-control', 'id' => 'mobile', 'maxlength' => 30]) !!}
                        </div>
                        <div class="form-group mb-4">
                            <label for="email">Correo</label>
                            {!! Form::text('email', null, ['class' => 'form-control', 'id' => 'email', 'maxlength' => 30]) !!}
                        </div>
                        <div class="form-group mb-4">
                            <label for="password">Contraseña</label>
                            {!! Form::password('password', ['class' => 'form-control', 'maxlength' => 20]) !!}
                        </div>

                    <div class="form-group mb-4">
                        <label for="password">Perfil</label>
                        {!! Form::select('role', $roles, '', ['class' => 'form-control']) !!}
                    </div>

                        <div class="d-flex justify-content-between">
                            <a href="{{ route('user.index') }}" class="btn btn-sm "> <i class="fas fa-arrow-circle-left"></i> Volver a lista de usuario</a>
                            <button type="submit" class="btn btn-primary"> <i class="fas fa-save"></i> Guardar</button>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            @if ($success)
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ $success }}
                </div>
            @endif
            <div class="card">
                <div class="card-header">Cuenta de usuario</div>
                <div class="card-body">
                    {!! Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'put']) !!}
                        @csrf
                        <div class="form-group mb-4">
                            <label for="name">Nombres</label>
                            {!! Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'maxlength' => 25]) !!}
                        </div>
                        <div class="form-group mb-4">
                            <label for="first_lastname">Apellido Paterno</label>
                            {!! Form::text('first_lastname', null, ['class' => 'form-control', 'id' => 'first_lastname', 'maxlength' => 20]) !!}
                        </div>
                        <div class="form-group mb-4">
                            <label for="second_lastname">Apellido Materno</label>
                            {!! Form::text('second_lastname', null, ['class' => 'form-control', 'id' => 'second_lastname', 'maxlength' => 20]) !!}
                        </div>
                        <div class="form-group mb-4">
                            <label for="mobile">Celular</label>
                            {!! Form::text('mobile', null, ['class' => 'form-control', 'id' => 'mobile', 'maxlength' => 30]) !!}
                        </div>
                        <div class="form-group mb-4">
                            <label for="email">Correo</label>
                            {!! Form::text('email', null, ['class' => 'form-control', 'id' => 'email', 'maxlength' => 30]) !!}
                        </div>
                        <div class="form-group mb-4">
                            <label for="password">Contraseña</label>
                            {!! Form::password('password', ['class' => 'form-control', 'maxlength' => 20]) !!}
                            <small>Dejar en blanco para conservar la contraseña actual</small>
                        </div>

                        <div class="d-flex justify-content-between">
                            <a href="{{ route('user.index') }}" class="btn btn-sm "> <i class="fas fa-arrow-circle-left"></i> Volver a lista de usuarios</a>
                            <button type="submit" class="btn btn-primary"> <i class="fas fa-save"></i> Guardar</button>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-between">
        <div class="col-md-12">
            <a href="{{ route('user.create') }}" class="btn btn-danger text-white"> <i class="fas fa-user-plus"></i> Crear nuevo usuario </a>
            <br><br>
            <!--Table-->
            <table id="tablePreview" class="table">
                <!--Table head-->
                <thead>
                <tr>
                    <th>#</th>
                    <th>Rol</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Correo</th>
                    <th>Celular</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <!--Table head-->
                <!--Table body-->
                <tbody>
                @if (count($users) > 0)
                    @foreach ($users as $user)
                    <tr>
                        <th scope="row">{{ $user->id }}</th>
                        <td>
                            @foreach ($user->roles as $role)
                            <span class="badge badge-primary badge-pill">{{ $role->name }}</span>
                            @endforeach
                        </td>
                        <td> {{ $user->name }} </td>
                        <td>{{ $user->first_lastname }} {{ $user->second_lastname }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->mobile }}</td>
                        <td class="row justify-content-between">
                            <a href="{{ route('user.edit', $user->id) }}" class="btn btn-sm btn-warning"><i class="fas fa-edit"></i> Editar</a>
                            <form action="{{route('user.destroy', $user->id)}}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                 @endif
                </tbody>
                <!--Table body-->
            </table>
            <!--Table-->
        </div>
    </div>
</div>
@endsection