routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'ReclamosController@index')->name('home');
Route::resource('user','UserController');
Route::resource('reclamos', 'ReclamosController');
Route::resource('configuraciones', 'SettingController');

Route::get('nuevo', 'ReclamosController@create');

Route::get('/ajax/crearcodigo', 'ReclamosController@ajxCrearCodigoReclamo');
Route::post('/ajax/registrar', 'ReclamosController@ajxRegistrarReclamo');
// Route::get('/ajax/inforeclamo', 'ReclamosController@ajxInfoReclamo');
// Route::get('/ajax/actualizarflagreclamo', 'ReclamosController@ajxActualizarFlagReclamo');

Route::get('/enviarmail','MailController@enviarEmail');

Route::any('/getcaptcha', 'CaptchaController@getCaptcha' );
Route::get('/refreshcapcha', 'CaptchaController@refreshCapcha');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <script src="https://kit.fontawesome.com/01a58d4c79.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-primary shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Sole') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link " href="{{ route('reclamos.index') }}">Reclamos</a></li>
                        <li class="nav-item"><a class="nav-link " href="{{ route('user.index') }}">Usuarios</a></li>
                        <li class="nav-item"><a class="nav-link " href="{{ route('configuraciones.index') }}">Configuración</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} {{ Auth::user()->first_lastname }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('user.edit', Auth::user()->id) }}"> {{ __('Cuenta') }}</a>
                                    <a class="dropdown-item text-danger" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Salir') }} <i class="fas fa-sign-out-alt"></i>
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/empty.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <script src="https://kit.fontawesome.com/01a58d4c79.js" crossorigin="anonymous"></script>
</head>
<body>
<div id="app">
    @yield('content')
</div>
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sole | Libro de Reclamaciones</title>

    <meta name="description" content="Sole | Libro de Reclamaciones" />
    <meta name="author" content="Pixellar" />

    <meta property="og:title" content="Sole | Libro de Reclamaciones" />
    <meta property="og:site_name" content="Sole | Libro de Reclamaciones" />
    <meta property="og:locale" content="es_ES" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="Sole | Libro de Reclamaciones" />

    <link rel="shortcut icon" href="{{ URL::asset('images/favicon.png') }}">

    <link href="{{ asset('css/master/normalize.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/master/foundation.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/master/site-style.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('js/vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('js/vendor/colorbox/colorbox.css') }}" rel="stylesheet" type="text/css"  media="screen">

    <script src="{{ asset('js/vendor/modernizr.js') }}"></script>
    <script src="{{ asset('js/vendor/jquery-2.1.4.min.js') }}"></script>
    <script src="{{ asset('js/vendor/json2.js') }}"></script>

</head>

<body>

<div class="site-container">

    <header>

        @if(Session::has('loggedUser'))
        <div class="header-box">
            <div class="upper-content">
                <div class="logo-left">
                    <a href="{{ URL::action("ReclamoController@buscarReclamo") }}"><img src="{{ URL::asset('images/logoWhite.png') }}" /></a>
                </div>
                <div class="session-info">
                    <div class="line-top">
                        bienvenido
                    </div>
                    <div class="line-middle">
                        {{ mb_strtoupper(Session::get('loggedUser')->nombre) }}
                    </div>
                    <div class="line-bottom">
                        ADMINISTRADOR
                    </div>
                </div>
                <div style="clear:both;"></div>
            </div>
            <div class="lower-content">
                <div class="site-grid-content">
                    <div class="row">
                        <div class="site-menu">
                            <div class="option-left">
                                <a href="{{ URL::action("ReclamoController@buscarReclamo") }}">inicio</a>
                            </div>
                            <div class="divider-left">
                                |
                            </div>
                            <div class="option-left">
                                <a href="{{ URL::action("UsuarioController@editarCuenta") }}">cuenta</a>
                            </div>
                            <div class="option-right">
                                <a href="{{ URL::action("UsuarioController@logout") }}">cerrar sesión</a>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>


        @endif

    </header>

    <div class="site-content">
        @yield('content')
    </div>

    <footer>

        @if(!Session::has('loggedUser'))
        <!--
        <div class="footer-box-index">
            <div class="texto">
                © Pontificia Universidad Católica del Perú - 2015. Todos los derechos reservados.<br>
                Av. Universitaria 1801, San Miguel, Lima 32, Perú | Teléfono (511) 626-2000
            </div>
        </div>

        <div class="footer-box-index-mobile">
            <div class="texto">
                © Pontificia Universidad Católica del Perú - 2015.<br>
                Todos los derechos reservados.<br>
                Av. Universitaria 1801, San Miguel, Lima 32, Perú <br>Teléfono (511) 626-2000
            </div>
        </div>
        -->
        @else
        <div class="footer-box">
            <div class="logo-left">
                <img src="{{ URL::asset('images/logoFooterSOLE.png') }}" />
            </div>
            <div class="options-content">
                <div class="option-right">
                    <a href="{{ URL::action("UsuarioController@logout") }}">cerrar sesión</a>
                </div>
                <div class="option-right">
                    <a href="{{ URL::action("UsuarioController@editarCuenta") }}">cuenta</a>
                </div>
                <div class="option-right">
                    <a href="{{ URL::action("ReclamoController@buscarReclamo") }}">inicio</a>
                </div>
            </div>
            <div style="clear:both;"></div>
        </div>

        <div class="footer-box-mobile">
            <div class="row fullWidth">
                <div class="columns small-12">
                    <div class="logo-content">
                        <img src="{{ URL::asset('images/logoFooterSOLE.png') }}" />
                    </div>
                </div>
                <div class="columns small-12">
                    <div class="options-content">
                        <div class="option">
                            <a href="{{ URL::action("UsuarioController@logout") }}">cerrar sesión</a>
                        </div>
                        <div class="option">
                            <a href="{{ URL::action("UsuarioController@editarCuenta") }}">cuenta</a>
                        </div>
                        <div class="option">
                            <a href="{{ URL::action("ReclamoController@buscarReclamo") }}">inicio</a>
                        </div>
                        <div style="clear:both;"></div>
                    </div>
                </div>
            </div>
        </div>

        @endif


    </footer>

</div>

<script src="{{ asset('js/site-script.js') }}"></script>
<script src="{{ asset('js/vendor/colorbox/jquery.colorbox-min.js') }}"></script>
<script src="{{ asset('js/foundation.min.js') }}"></script>
<script>
    $('.site-grid-content').foundation();
</script>

</body>
</html>