routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'ReclamosController@index')->name('home');
Route::resource('user','UserController');
Route::resource('reclamos', 'ReclamosController');
Route::resource('configuraciones', 'SettingController');

Route::get('nuevo', 'ReclamosController@create');

Route::get('/ajax/crearcodigo', 'ReclamosController@ajxCrearCodigoReclamo');
Route::post('/ajax/registrar', 'ReclamosController@ajxRegistrarReclamo');
// Route::get('/ajax/inforeclamo', 'ReclamosController@ajxInfoReclamo');
// Route::get('/ajax/actualizarflagreclamo', 'ReclamosController@ajxActualizarFlagReclamo');

Route::get('/enviarmail','MailController@enviarEmail');

Route::any('/getcaptcha', 'CaptchaController@getCaptcha' );
Route::get('/refreshcapcha', 'CaptchaController@refreshCapcha');

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    public $timestamps = false;
}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $settings = Setting::all();

        return view('settings.index', compact('settings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function show(Setting $setting)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $setting = Setting::findOrFail($id);
        $success = false;

        return view('settings.edit', compact('setting', 'success'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $success = false;

        $request->validate([
            'key' => 'required|min:5|max:30',
            'value' => 'required',
        ]);

        $setting = Setting::findOrFail($id);
        $setting->key = $request->key;
        $setting->value = $request->value;
        $setting->save();

        if ($setting->save()) {
            $success = 'Actualizado correctamente';
        }
        return view('settings.edit', compact('setting', 'success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function destroy(Setting $setting)
    {
        //
    }
}

resources/views/settings/edit.blade.php
@extends('layouts.app')

@section('content')
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
@if ($success)
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ $success }}
</div>
@endif

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Modificar Configuración</div>
                <div class="card-body">
                    {!! Form::model($setting, ['route' => ['configuraciones.update', $setting->id], 'method' => 'put']) !!}
                    @csrf
                    <div class="form-group mb-4">
                        <label for="Key">Key</label>
                        {!! Form::text('key', null, ['class' => 'form-control', 'id' => 'key', 'maxlength' => 30]) !!}
                    </div>
                    <div class="form-group mb-4">
                        <label for="value">Value</label>
                        {!! Form::textarea('value', null, ['class' => 'form-control', 'id' => 'value']) !!}
                    </div>

                    <div class="d-flex justify-content-between">
                        <a href="{{ route('configuraciones.index') }}" class="btn btn-sm "> <i class="fas fa-arrow-circle-left"></i> Volver a lista de configuraciones</a>
                        <button type="submit" class="btn btn-primary"> <i class="fas fa-save"></i> Guardar</button>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/settings/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-between">
        <div class="col-md-12">
            <!-- <a href="{{ route('configuraciones.create') }}" class="btn btn-danger text-white"> <i class="fas fa-user-plus"></i> Crear nuevo </a> -->
            <br><br>
            <!--Table-->
            <table id="tablePreview" class="table">
                <!--Table head-->
                <thead>
                <tr>
                    <th>#</th>
                    <th>Key</th>
                    <th>Value</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <!--Table head-->
                <!--Table body-->
                <tbody>
                @if (count($settings) > 0)
                @foreach ($settings as $setting)
                <tr>
                    <th scope="row">{{ $setting->id }}</th>
                    <td>{{ $setting->key }}</td>
                    <td>{{ $setting->value }}</td>
                    <td class="row justify-content-between">
                        <a href="{{ route('configuraciones.edit', $setting->id) }}" class="btn btn-sm btn-warning"><i class="fas fa-edit"></i> Editar</a>
                        <form action="{{route('configuraciones.destroy', $setting->id)}}" method="POST">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach
                @endif
                </tbody>
                <!--Table body-->
            </table>
            <!--Table-->
        </div>
    </div>
</div>
@endsection